# fly.toml app configuration file generated for nemdl on 2023-08-25T22:58:17-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nemdl"
primary_region = "dfw"

[build]
  image = "ghcr.io/frankgx97/nem-downloader:master"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
